name: CD

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: executing remote ssh commands using password
      uses: fifsky/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        user: ${{ secrets.SSH_USER }}
        pass: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        command: |
          ls -al