name: Java

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Build & Push to Docker Hub
      uses: opspresso/action-docker@master
      env:
        USERNAME: ${{ secrets.DOCKER_USERNAME }}
        PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
        IMAGE_NAME: "logicrain/kgdrug"
        TAG_NAME: "v0.0.1"
        LATEST: "true"
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          whoami
          ls -al